Draft: Pr graduation
spack/spackbot pull request #68
Opened 2022-09-30 18:57 UTC by kwryankrattiger

@scottwittenburg

Reviving #45

2022-10-14 19:12 UTC, scottwittenburg commented on spackbot/routes.py
> +    await handlers.graduate_pr_binaries(event, gh)
I think `handlers/__init__.py` still needs to import this to make it available as you've invoked it here.

2022-10-14 19:13 UTC, scottwittenburg commented on spackbot/routes.py
> +    await handlers.graduate_pr_binaries(event, gh)
so i.e.:

```
from .mirrors import graduate_pr_binaries
```

2022-11-08 19:01 UTC, scottwittenburg requested changes
Thanks @kwryankrattiger, this looks like a lot of work, but is coming along nicely.  I have added what I think are mostly questions, but also some requests.  Hopefully you can straighten me out where I'm not getting it.

Also, a blanket request to apply to the change as a whole:  Can you add docstrings to the new methods and describe the behavior of the methods, as well as expected inputs, and outputs?

Also, before it's all over, you're going to need to run `black` on your changes to get this to pass the style check.  Just install it with `pip` and run `black .` from the top level of the repo, or maybe from the `spackbot` directory, I forget.

2022-11-08 22:03 UTC, kwryankrattiger commented on spackbot/workers.py
> +            )
I also dislike this API...quite a shame

2022-11-08 22:14 UTC, scottwittenburg commented on spackbot/workers.py
> +                    obj.delete()
Ok, as you pointed out, this is just a naming confusiong on my part.  I saw the `pr_bucket` variable in the loop and assumed it was the mirror for PR, not the shared pr mirror, but I get it now.  I think the argument to the method should be called `shared_pr_mirror_url` and all the `pr_...` things changed to `shared_pr...` for clarity though.

2022-11-08 22:14 UTC, scottwittenburg commented on spackbot/workers.py
> +                # Get the hashes in the shared PR bucket.
Nvm, this is more naming confusion on my part.

2022-11-08 22:34 UTC, kwryankrattiger commented on spackbot/workers.py
> +                if not obj.key.endswith(extensions):
Skipping .spack is just to avoid duplicates, but it isn't strictly necessary since it is a set.

2022-11-11 20:16 UTC, scottwittenburg approved these changes
Looks good to me, thanks for getting this done!

2022-11-11 22:07 UTC, merged